<?php

/**
 * Implements hook_permissions().
 */
function views_form_attendance_activity_create_permissions() {
  return [
    'administer attendence activity create' => [
      'title' => t('Administer Views Form Attendance Activity Create'),
      'description' => t('Perform administration tasks Views Form Attendance Activity Create.'),
    ],
  ];
}

/**
 * Implements hook_views_api().
 */
function views_form_attendance_activity_create_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_form_attendance_activity_create') . '/views',
  );
}

/**
 * Utility function to get the option values for the Attendance custom field
 */
function _views_form_attendance_activity_create_get_attendance_value_options() {
  if (!civicrm_initialize()) {
    return [];
  }
  $options = [];
  try {
    $attendance_custom_field = variable_get('views_form_attendance_activity_create_attendance_cf_id', '');
    if (!empty($attendance_custom_field)) {
      $result = civicrm_api3('Activity', 'getoptions', [
        'sequential' => 1,
        'field'      => $attendance_custom_field,
      ]);
      if (!empty($result['count'])) {
        foreach ($result['values'] as $index => $value_data) {
          $options[$value_data['key']] = $value_data['value'];

        }
      }
    }
  }
  catch (Exception $e) {
  }
  return $options;
}

/**
 * Utility function to get the option values for the Attendance Activity custom field
 */
function _views_form_attendance_activity_create_get_activity_cf_value_options() {
  if (!civicrm_initialize()) {
    return [];
  }
  $options = [];
  try {
    $activity_custom_field = variable_get('views_form_attendance_activity_create_attendance_activity_cf_id', '');
    if (!empty($activity_custom_field)) {
      $result = civicrm_api3('Activity', 'getoptions', [
        'sequential' => 1,
        'field'      => $activity_custom_field,
      ]);
      if (!empty($result['count'])) {
        foreach ($result['values'] as $index => $value_data) {
          $options[$value_data['key']] = $value_data['value'];

        }
      }
    }
  }
  catch (Exception $e) {
  }
  return $options;
}


/**
 * Utility function to get options for Activity Types
 *
 * @return array
 */
function _views_form_attendance_activity_create_get_activity_type_options() {
  $options = [];
  if (civicrm_initialize()) {
    try {
      $result = civicrm_api3('OptionValue', 'get', [
        'sequential' => 1,
        'option_group_id' => "activity_type",
        'options' => ['limit' => 0],
      ]);
      if (!empty($result['count'])) {
        foreach ($result['values'] as $index => $value_data) {
          $options[$value_data['value']] = $value_data['label'];
        }
      }
    }
    catch (Exception $e) {
    }
  }

  return $options;
}

/**
 * Utility function to get contact_id of a user
 *
 * @param $account
 * @return int
 */
function _views_form_attendance_activity_create_get_user_cid($account = []) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }
  if (civicrm_initialize() && !empty($account->uid)) {
    try {
      $result = civicrm_api3('UFMatch', 'get', array(
        'sequential' => 1,
        'uf_id' => $account->uid,
      ));
      if (!empty($result['count'])) {
        return $result['values'][0]['contact_id'];
      }
    }
    catch (Exception $e) {
    }
  }
  return 0;
}
