<?php

/**
 * @file
 * Install file for Views Form Attendance Activity Create
 */

/**
 * Remove unnecessary variables
 */
function views_form_attendance_activity_create_update_7001(&$sandbox) {
  variable_del('views_form_attendance_activity_create_attendance_cf_id');
  variable_del('views_form_attendance_activity_create_activity_type');
  variable_del('views_form_attendance_activity_create_attendance_date_cf_id');
  variable_del('views_form_attendance_activity_create_attendance_activity_cf_id');
}
